### ISSUE TITLE
No Source Code Available?

### ISSUE THREAD

**Issue by bpfeffer** [RWilton/Arioc#1]
I'm having an issue compiling on centos because my glibc is 2.12 and it requires 2.14 in the precompiled version. So I went to download the source code and all 3 versions(both zips per) don't have the source code and only have a manual and some attribute files.

Am I missing something or do you have an idea on how to run despite the wrong glibc version?

**Comment by RWilton** [comment]
Hello --

The Arioc sources are in Arioc.104.zip (about 720KB), under "Releases".

As for getting the precompiled binaries to run with an earlier version of glibc:  please don't bother.  It's easier to recompile from source.

If that doesn't work for you, please let me know.

Richard Wilton

**Comment by bpfeffer** [comment]
I installed a second copy of glibc(2.14) in /opt/newglibc and then when I run the program, I use the commandline:
LD_LIBRARY_PATH=/opt/newglibc ./AriocE
And it uses the newer library for that execution, software is working now.

**Comment by RWilton** [comment]
Thank you for the tip on getting the precompiled Arioc binaries to run.

If you have a moment, I would be grateful if you could send me a bit of performance data with your setup.  A dump of the output from AriocU or AriocP (plus a few tidbits like CPU clock speed and disk I/O bandwidth) ought to contain enough information.

Good luck!
- rw
