### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by r-barnes** [RWilton/Arioc#12]
There doesn't appear to be any source code in the repo. Could you double-check that you've pushed appropriately?

**Comment by RWilton** [comment]
Source code is in the zip files in the current release.

**Comment by r-barnes** [comment]
This is very non-standard and makes it more difficult to suggest bug fixes or compare versions of the code.

**Comment by RWilton** [comment]
Arioc is "open source," but like all of the most widely used short read sequence aligners it is not a collaborative public project that is open to "tinkerers" and folks who have no stake in maintaining a robust and reliable code base.  We use github for source code distribution and public versioning, and we very much appreciate bug reports and good ideas about functionality — but we prefer to fix bugs and implement new features ourselves.

This is admittedly a rather conservative policy, but over the years it has helped to ensure reliable and consistent functionality for a user base that quite reasonably demands it.
