### ISSUE TITLE
Suppress @SQ metadata header for aggregated FASTA file

### ISSUE THREAD

**Issue by RWilton** [RWilton/Arioc#23]
Ok, used this reference for mapping a WGS file, seemed to work OK, even did GATK base quality recalibration on the resulting BAM. However, after that i want to use Manta to find structural variations, but it balks at the bam with:
`  Reference genome mismatch: Reference fasta file is missing a chromosome found in the Tumor BAM/CRAM file: '0.101#3341'
`
Looking into the header of the bam i do find a SQ line:
`@SQ	SN:0.101#3341	LN:129060516	UR:https://console.cloud.google.com/storage/browser/_details/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta/others.fa	rm:(multiple reference sequences)	`
This @SQ describes the file i put all the decoys in. The line is followed by @SQ lines for all the chromosomes in that file so that looks OK, but i am pretty sure it should not add an extra @sq line for the file itself.
I tried to remove the superfluous  @SQ line from the bam with samtools reheader (just removing the one line) but then indexing the bam fails with:
`samtools index -@16 K274_16.bam 
samtools index: failed to create index for "K274_16.bam": Numerical result out of range
`
i checked with "samtools view K274_16.bam 0.101#3341", and there are no reads mapped to this @SQ.
So, it seems currently i cant use this bam for Manta. I cant remove the @SQ line. 
Dont know what to do now.

_Originally posted by @karlkashofer in https://github.com/RWilton/Arioc/issues/20#issuecomment-955599199_

**Comment by RWilton** [comment]
Hello Karl --

I am sorry you have run into a SAM/BAM formatting problem.  Let's see if we can figure out a workaround and maybe that will lead to a more definitive solution.

The first question pertains to the "superfluous" `@SQ` record in the SAM file.  Unfortunately, there is nothing explicit in the SAM/BAM format specification about the relationship between `@SQ-SN` (the sequence name tag in `@SQ`) and the `RNAME` field in alignment records.  Intuitively, you would assume that each `RNAME` must refer to a unique corresponding `@SQ-SN` (and in fact the spec points this out somewhere, sort of).

But the spec contains no inverse requirement, that is, there is no requirement for every `@SQ-SN` to correspond to at least one `RNAME`.  Such a requirement would be very hard on aligners as well as on tools that filter reads out of SAM/BAM files, since such tools would need to keep track of which `@SQ-SN` records were actually referenced by at least one `RNAME` in order to know which `@SQ` records to include in the output.

So, for an "aggregated" FASTA that contains multiple deflines, Arioc assumes that it's ok to write a `@SQ-SN` that provides metadata for the entire FASTA file.  (Where else could you possibly put that metadata, anyway?)  We know that this `@SQ`'s `SN` can never be referenced by an `RNAME` -- in fact, the `SN` string is just a placeholder -- so all is well, or should be.

Unfortunately, you now need to use a tool that seems to be unable to deal with such a SAM file.  So how do we handle this?

I could change Arioc so that it doesn't emit the `@SQ-SN` for the aggregated FASTA file.  I suppose it could be turned into a `@CO` record or just omitted altogether.  I could do that next week if you want to wait.

Or you could spend five minutes creating a little FASTA file for SN:0.101#3341, containing nothing but a defline and some Ns.  (Who cares what's in it?  Nothing references it anyway.)  Hand that off to Manta and see if it's satisfied.

As for the worthless error message from _samtools index_:  what can I say?  You gave _samtools reheader_ a valid SAM/BAM file and it emitted something that _samtools index_ can't deal with.  I wouldn't spend more than a few minutes troubleshooting that, just to be sure that I hadn't made a parameterization error somewhere.  Then I would just pipe the original SAM/BAM file through _grep_ or maybe _sed_ to remove the line that contains "SN:0.101#3341".  I would double-check the resulting SAM output to be 100% sure that it looked right (i.e., just that one header line removed).  And I would then feed that to Manta and see what happens.

So let me know what you think, and how you'd like to approach this problem.  I'll try to help if I can, and as I said, I should be able to change Arioc to suppress that `@SQ` record in the next week or so.

· rw

_Originally posted by @RWilton in https://github.com/RWilton/Arioc/issues/20#issuecomment-955637032_

**Comment by RWilton** [comment]
Hi Richard !
I removed the offending @SQ line (samtools view A274_16.bam | cat header.txt - | samtools view -b > A274_16.fixed.bam) which took a while, and Manta is finally happy with the bam file. Thus i would really appreciate if you could modify Arioc to suppress these @SQ lines.

_Originally posted by @karlkashofer in https://github.com/RWilton/Arioc/issues/20#issuecomment-956481975_

**Comment by RWilton** [comment]
Done.

Please download build 3040, which supports an "extra" parameter named `suppressRaggSQ` that suppresses the output of the `@SQ` metadata header record for a FASTA file in which multiple reference sequences are aggregated.  To use this parameter, place it in the `<X>` element in the AriocU or AriocP configuration file:

`<X suppressRaggSQ="1" />`

The file _Xparams.txt_ in the Arioc distribution provides additional information.

If this approach doesn't work for you, please don't hesitate to open a new github issue!

_Originally posted by @RWilton in https://github.com/RWilton/Arioc/issues/20#issuecomment-962541317_

**Comment by RWilton** [comment]
Hi Richard ! I tried using this parameter, it works and suppresses the @SQ line for the aggregated file. However, it seems to also suppress the @SQ lines for normal, not aggregated FASTA reference files leading to missing @SQ lines and SAM errors.

This is part of my AriocE cfg:
`<file SN="chrY"  subId="24">chrY.fa</file>`
`<file SN="chrM" subId="25">chrM.fa</file>`
`<file SN="(*) *" subId="101">others.fa</file>`

With this latest version and suppressRaggSQ="1" i get no SQ line for chrY and chrM (bad), no SQ line for "others.fa" (which is good), and correct SQ lines for the contigs inside of others.fa.

_Originally posted by @karlkashofer in https://github.com/RWilton/Arioc/issues/20#issuecomment-968127776_

**Comment by RWilton** [comment]
@karlkashofer I am sorry there is a bug in this new functionality.  In my testing, the `suppressRaggSQ` parameter produced the desired effect, so I must have missed something!

Could you please verify that the two FASTA files in question come from GRCh38?  And are you using the other 23 FASTA files (chr1-chr22, chrX) associated with that reference genome?

**Comment by karlkashofer** [comment]
Hi ! Trying latest build:
```
 AriocP ./ariocP.1026027
185155019 [00000031] AriocP v1.50.3053.21328 (release) +2021-11-24T11:46:19
185155021 [00000031] Copyright (c) 2015-2021 Johns Hopkins University.  All rights reserved.
185155021 [00000031]  compiled             : 2021-11-25T11:20:16 (GNU g++ v10.2.1)
185155021 [00000031]  data type sizes      : int=4 long=8 *=8 Jvalue5=5 Jvalue8=8 JtableHeader=5 (little-endian)
185155021 [00000031]  computer name        : 5ae077f55d9b
185155021 [00000031]  operating system     : Debian GNU/Linux 11 (bullseye)
185155021 [00000031]  executable file      : /analysis/AriocP
185155021 [00000031]  configuration file   : /analysis/ariocP.1026027
185155317 [00000031] AriocBase::loadR: load R from disk...
...
```

using this in config:

```
<AriocP gpuMask="0x0000000F" batchSize="16k">
  <X suppressRagSQ="1" />
  <R>/scratch/AriocR/</R>
```

does not work. The offending @SQ is still in the SAM header, together with all other, correct lines.

btw: these extra @SQ lines also prevent storing in CRAM:
```
Starting merge at Thu Nov 25 18:49:14 UTC 2021
+ samtools fixmate -@8 -u -m - -
+ samtools sort -u -m1G -@8 -T /scratch/tmp -
+ samtools markdup -T /scratch/tmp -@8 -O bam,level=0 - -
+ samtools view -@8 --write-index -C -T /scratch/karl/arioc/R/GATK/Homo_sapiens_assembly38.fasta -o ./test.cram -
+ samtools merge -c -p -r -@8 -u - BSF_0941.subsampled.bam.1026025.sam/BSF_0941.subsampled.bam.1026025.bam
[bam_sort_core] merging from 0 files and 8 in-memory blocks...
[E::fai_build3_core] Failed to open the file https://console.cloud.google.com/storage/browser/_details/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta/others.fa
[E::refs_load_fai] Failed to open reference file 'https://console.cloud.google.com/storage/browser/_details/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta/others.fa'
[E::cram_get_ref] Failed to populate reference for id 25
[main_samview] failed to write the SAM header

```

**Comment by RWilton** [comment]
Please try `suppressRaggSQ="1"` .  (The abbreviation "Ragg" stands for "R-sequence aggregate.")

Thanks...

**Comment by karlkashofer** [comment]
Yes, thats much better !

But, please update line 103 in Xparams.txt    :)

**Comment by karlkashofer** [comment]
This is now confirmed working, please close, thanks a lot !

**Comment by RWilton** [comment]
Yikes!  Thank you for finding that typo.

Please let me know if any other problems arise in regard to those "orphan" `@SQ` headers.
