### ISSUE TITLE
Error when running AriocP

### ISSUE THREAD

**Issue by wabrashear** [RWilton/Arioc#28]
I'm trying to get Arioc working with the the example data for GRCh38. I'm getting this error when running AriocP for the paired end data using the provided cfg file: 

ApplicationException ([0x03680784] AriocCommon/InputFileGroup.cpp 612): inconsistent value for attribute srcId= for ../../Q/G
RCh38/enc.paired/i100p_1$a21.sbf: expected 1 specified 0

**Comment by RWilton** [comment]
The error indicates that `srcId="1"` was specified in the AriocE configuration file for the encoded reads whereas `srcId="0"` was specified where those encoded reads were referenced in the AriocP configuration file.  The value for the `srcId` attribute must be the same in both places.

If that doesn't help you resolve the problem, then please feel free to post or email your .cfg files and we'll try to help you figure it out.

**Comment by wabrashear** [comment]
That worked. Thank you!
