### ISSUE TITLE
HOWTO?

### ISSUE THREAD

**Issue by dakami** [RWilton/Arioc#3]
I have two fastq files for a paired WGBS read, as well as hg38.fa.

It's not clear what the sequence of operations is, to go from this, to a SAM or a BAM file.  Could you assemble a quick HOWTO or a very simple cfg?  For example, how do I generate gapped or ungapped seeds?

**Comment by RWilton** [comment]
This is documented in the Arioc user guide.  Working samples for both S cerevisiae and H sapiens are provided in both the Windows and Linux downloads.
