### ISSUE TITLE
ApplicationException during BS-seq alignment

### ISSUE THREAD

**Issue by claus-h-g** [RWilton/Arioc#38]
After ensuring that Arioc operates correctly with the sample reference and read data provided on a small test system, I wanted to use Arioc for mapping paired end BS sequencing data.

I did get started with example files of 1 Mio reads, trimming adapter sequences (in a new conda environment) with
trim_galore /path/to/B2021_9857_1_Mio_1.fq.gz

and 👍
trim_galore /path/to/B2021_9857_1_Mio_2.fq.gz

Both reads were encoded  with AE_B2021_9857_1_Mio_1_val_paired.cfg. this is attached as a txt file
[AE_B2021_9857_1_Mio_1_val_paired.cfg.txt](https://github.com/user-attachments/files/17936716/AE_B2021_9857_1_Mio_1_val_paired.cfg.txt)

Running:
$ /applications/Arioc/bin/AriocE AE_B2021_9857_1_Mio_1_val_paired.cfg

163758585 [0000deeb] AriocE v1.52.3144.24264 (release) +2024-09-20T22:26:45
163758587 [0000deeb] Copyright (c) 2015-2024 Johns Hopkins University.  All rights reserved.
163758587 [0000deeb]  compiled             : 2024-11-15T16:16:42 (GNU g++ v9.4.0)
163758587 [0000deeb]  data type sizes      : int=4 long=8 *=8 Jvalue5=5 Jvalue8=8 JtableHeader=5 (little-endian)
163758587 [0000deeb]  computer name        : meqneuopat24
163758587 [0000deeb]  operating system     : Ubuntu 20.04.6 LTS
163758587 [0000deeb]  executable file      : /applications/Arioc/bin/AriocE
163758587 [0000deeb]  configuration file   : /home/minknow/2024_11_20_Arioc/AE_B2021_9857_1_Mio_1_val_paired.cfg
163758587 [0000deeb] AriocE::encodeQ: encoding 2 files (8 CPU threads available)...
163800467 [0000def6] tuEncodeFASTQ::summarizeReadLengthDistribution: /home/minknow/B2021_9857_1_Mio_1_trimmed.fq: 999985 reads [21-101 mean (sd) 99.6 (4.6)]
163800468 [0000def6] tuEncodeFASTQ::summarizeC3Distribution: /home/minknow/B2021_9857_1_Mio_1_trimmed.fq: 999985 reads [1-69 mean (sd) 39.6 (5.0)]
163800468 [0000def7] tuEncodeFASTQ::summarizeReadLengthDistribution: /home/minknow/B2021_9857_1_Mio_2_trimmed.fq: 999900 reads [20-101 mean (sd) 99.6 (4.8)]
163800468 [0000def7] tuEncodeFASTQ::summarizeC3Distribution: /home/minknow/B2021_9857_1_Mio_2_trimmed.fq: 999900 reads [1-69 mean (sd) 39.6 (5.2)]
163800478 [0000deeb] AriocE::encodeQ: encoded 2 files
163800478 [0000deeb] AriocE::validateQ: validating 2 files (8 CPU threads available)...
163800478 [0000defc] tuValidateQ::validateQNAME: /home/minknow/2024_11_20_Arioc/fastqEnc/B2021_9857_1_Mio_1_trimmed$sqm.sbf: 0x0000000800000000 'A00684:136:HJN7VDRXY:2:1216:29767:17253'
163800478 [0000defd] tuValidateQ::validateQNAME: /home/minknow/2024_11_20_Arioc/fastqEnc/B2021_9857_1_Mio_2_trimmed$sqm.sbf: 0x0000000800000001 'A00684:136:HJN7VDRXY:2:1216:29767:17253'
163800543 [0000deeb] AriocE::validateQ: validated 2 files
163800543 [0000deeb] AriocE ends (0)

Mapping was attempted with: AP_B21_9857_1_Mio_1_val_paired.cfg (attached as well as a txt:
[AP_B21_9857_1_Mio_1_val_paired.cfg.txt](https://github.com/user-attachments/files/17936736/AP_B21_9857_1_Mio_1_val_paired.cfg.txt)
)

I did encounter the memory error running

 /applications/Arioc/bin/AriocP AP_B21_9857_1_Mio_1_val_paired.cfg 
172309429 [0000e2c5] AriocP v1.52.3144.24264 (release) +2024-09-20T22:26:45
172309433 [0000e2c5] Copyright (c) 2015-2024 Johns Hopkins University.  All rights reserved.
172309433 [0000e2c5]  compiled             : 2024-11-15T16:22:32 (GNU g++ v9.4.0)
172309433 [0000e2c5]  data type sizes      : int=4 long=8 *=8 Jvalue5=5 Jvalue8=8 JtableHeader=5 (little-endian)
172309433 [0000e2c5]  computer name        : meqneuopat24
172309433 [0000e2c5]  operating system     : Ubuntu 20.04.6 LTS
172309433 [0000e2c5]  executable file      : /applications/Arioc/bin/AriocP
172309433 [0000e2c5]  configuration file   : /home/minknow/2024_11_20_Arioc/AP_B21_9857_1_Mio_1_val_paired.cfg
172309713 [0000e2c5] AriocBase::loadR: load R from disk...
172314052 [0000e2c5] AriocBase::loadR: loaded 25 R sequences: 2358955464 bytes (2.2GB) from 50 files in 4339ms (518.5MB/s)
172314052 [0000e2c5] AriocBase::loadHJ: load H and J LUTs from disk...
172314052 [0000e2db] CudaPinnedPtr<T>::Realloc: cudaHostAlloc( ..., 5368709120 bytes, ... ) on thread 58075
172316018 [0000e2db] CudaPinnedPtr<T>::Realloc: back from cudaHostAlloc()
172326039 [0000e2eb] CudaPinnedPtr<T>::Realloc: cudaHostAlloc( ..., 28623477756 bytes, ... ) on thread 58091
172336307 [0000e2eb] CudaPinnedPtr<T>::Realloc: back from cudaHostAlloc()
172429796 [0000e34f] CudaPinnedPtr<T>::Realloc: cudaHostAlloc( ..., 5368709120 bytes, ... ) on thread 58191
172431949 [0000e34f] CudaPinnedPtr<T>::Realloc: back from cudaHostAlloc()
172441978 [0000e366] CudaPinnedPtr<T>::Realloc: cudaHostAlloc( ..., 28711564312 bytes, ... ) on thread 58214
172441982 [0000e366] ApplicationException ([0x00058214] AriocBase/../CudaCommon/CudaPinnedPtr.h 105): Unable to allocate page-locked system memory (CUDA "pinned" memory).  Please ensure that there is sufficient system memory to execute this program.

The XUbuntu 20.04 test system has 64 GB RAM and additional 64 GB of SWAP and a NVIDIA GeForce RTX 2070.
During the run in nvtop I do see that 1% of the GPU memory (96 MB) are used but 0% of GPU processing are used.

After a short while, I encountered the following error:
“172441982 [0000e366] ApplicationException ([0x00058214] AriocBase/../CudaCommon/CudaPinnedPtr.h 105): Unable to allocate page-locked system memory (CUDA "pinned" memory).  Please ensure that there is sufficient system memory to execute this program.”

How can I solve this issue?

P.S. Sorry I just realized that the XML files are partially truncated after pasting them in this text box. I attached them with an additional txt extension (as *.cfg.txt).

**Comment by RWilton** [comment]
I am sorry you encountered an out-of-memory error with Arioc.

Could you please confirm the amount of GPU memory available in your GPU device?  I have never run AriocP on an RTX 2070, but from what I see in its hardware specifications, there are only 8GB of memory available on that device.  That would probably be insufficient to contain both the memory the memory required to compute alignments and the lookup tables for nongapped and gapped seeds.

You can add some diagnostic flags to your AriocP.cfg to see how Arioc is allocating GPU memory.  For example,

`<AriocP gpuMask="0x00000001" batchSize="24k" verboseMask="0xE0004007">`

Post the resulting output log and we can troubleshoot the problem together.

**Comment by claus-h-g** [comment]
Many thanks for your rapid reply.

Using 
AriocP gpuMask="0x00000001" batchSize="24k" verboseMask="0xE0004007"

I did create the attached [mod_AP_B21_9857_1_Mio_1_val_paired.cfg.txt](https://github.com/user-attachments/files/17946473/mod_AP_B21_9857_1_Mio_1_val_paired.cfg.txt) and ran:

minknow@meqneuopat24:~/2024_11_20_Arioc$ /applications/Arioc/bin/AriocP mod_AP_B21_9857_1_Mio_1_val_paired.cfg.txt 
105923595 [0004b553] AriocP v1.52.3144.24264 (release) +2024-09-20T22:26:45
105923598 [0004b553] Copyright (c) 2015-2024 Johns Hopkins University.  All rights reserved.
105923598 [0004b553]  compiled             : 2024-11-15T16:22:32 (GNU g++ v9.4.0)
105923598 [0004b553]  data type sizes      : int=4 long=8 *=8 Jvalue5=5 Jvalue8=8 JtableHeader=5 (little-endian)
105923598 [0004b553]  computer name        : meqneuopat24
105923598 [0004b553]  operating system     : Ubuntu 20.04.6 LTS
105923598 [0004b553]  executable file      : /applications/Arioc/bin/AriocP
105923598 [0004b553]  configuration file   : /home/minknow/2024_11_20_Arioc/mod_AP_B21_9857_1_Mio_1_val_paired.cfg.txt
105923784 [0004b553]  max CPU threads      : *
105923784 [0004b553]  number of GPUs       : 1 (mask: 0x00000001)
105923784 [0004b553]  batch size           : 24k (24576)
105923784 [0004b553]  R sequence path      : /home/minknow/2024_11_20_Arioc/enc
105923784 [0004b553]   DNA base conversion : CT
105923784 [0004b553]  nongapped aligner:
105923784 [0004b553]   seed                : ssi84_2_30_CT
105923784 [0004b553]    hashSeedWidth      : 84
105923784 [0004b553]    spacedSeedWeight   : 48
105923784 [0004b553]    maxMismatches      : 2
105923784 [0004b553]    hashKeyWidth       : 30
105923784 [0004b553]   big-bucket threshold: *
105923784 [0004b553]   maxJ                : *
105923784 [0004b553]   seedCoverage        : *
105923784 [0004b553]  gapped aligner:
105923784 [0004b553]   seed                : hsi20_0_30_CT
105923784 [0004b553]    hashSeedWidth      : 20
105923784 [0004b553]    hashKeyWidth       : 30
105923784 [0004b553]   W scores/penalties  : 2,6,5,3
105923784 [0004b553]    Wm (match)         : 2
105923784 [0004b553]    Wx (mismatch)      : 6
105923784 [0004b553]    Wg (gap)           : 5
105923784 [0004b553]    Ws (gap space)     : 3
105923784 [0004b553]    Wn (N)             : 6
105923784 [0004b553]    Wc (clip penalty)  : 0
105923784 [0004b553]    Vt (threshold)     : 100
105923784 [0004b553]   big-bucket threshold: 200
105923784 [0004b553]   maxJ                : 200
105923784 [0004b553]   AtO                 : 1
105923784 [0004b553]   seedDepth           : 6
105923784 [0004b553]   minPosSep           : 5
105923784 [0004b553]   mapqVersion         : 0 (Arioc default)
105923784 [0004b553]   XM soft clip context: excluded
105923784 [0004b553]   XM BQS threshold    : 0
105923784 [0004b553]  paired-end reads
105923784 [0004b553]   orientation         : convergent
105923784 [0004b553]   collisions          : overlap,cover
105923784 [0004b553]   fragment length     : 0-1000
105923784 [0004b553]   reporting           : unmapped,concordant
105923784 [0004b553]   maxAperRead         : 1
105923784 [0004b553]   seed rev complement : true
105923784 [0004b553]  Q sequences (reads)  : (2 files, paired)
105923784 [0004b553]   nominal sub rate    : 0.25%
105923784 [0004b553]   00000.001 mate 1    : /home/minknow/2024_11_20_Arioc/fastqEnc/B2021_9857_1_Mio_1_trimmed$a21.sbf
105923784 [0004b553]   00000.001 mate 2    : /home/minknow/2024_11_20_Arioc/fastqEnc/B2021_9857_1_Mio_2_trimmed$a21.sbf
105923784 [0004b553]  A (alignment output) : (1 path, 1073741824 mappings per output file, output file base name: AriocP)
105923784 [0004b553]   SAM                 : /home/minknow/2024_11_20_Arioc/SAM (unmapped,concordant)
105923784 [0004b553]   cigarFormat         : =XIDS
105923784 [0004b553]   mdFormat            : standard
105923838 [0004b553] AriocBase::loadR: load R from disk...
105928190 [0004b553] AriocBase::loadR: loaded 25 R sequences: 2358955464 bytes (2.2GB) from 50 files in 4352ms (516.9MB/s)
105928190 [0004b553] AriocBase::loadHJ: load H and J LUTs from disk...
105928191 [0004b56f] CudaPinnedPtr<T>::Realloc: cudaHostAlloc( ..., 5368709120 bytes, ... ) on thread 308591
105930177 [0004b56f] CudaPinnedPtr<T>::Realloc: back from cudaHostAlloc()
105940200 [0004b56f] tuLoadLUT<T>::main: loaded 5368709120 bytes (5.0GB) in 12010ms (426.3MB/s) from /home/minknow/2024_11_20_Arioc/enc/ssi84_2_30_CT/H230.sbf
105940201 [0004b58f] CudaPinnedPtr<T>::Realloc: cudaHostAlloc( ..., 28623477756 bytes, ... ) on thread 308623
105951212 [0004b58f] CudaPinnedPtr<T>::Realloc: back from cudaHostAlloc()
110047853 [0004b58f] tuLoadLUT<T>::main: loaded 28623477755 bytes (26.7GB) in 67652ms (403.5MB/s) from /home/minknow/2024_11_20_Arioc/enc/ssi84_2_30_CT/J230.sbf
110047855 [0004b65d] CudaPinnedPtr<T>::Realloc: cudaHostAlloc( ..., 5368709120 bytes, ... ) on thread 308829
110050527 [0004b65d] CudaPinnedPtr<T>::Realloc: back from cudaHostAlloc()
110100703 [0004b65d] tuLoadLUT<T>::main: loaded 5368709120 bytes (5.0GB) in 12848ms (398.5MB/s) from /home/minknow/2024_11_20_Arioc/enc/hsi20_0_30_CT/H030.sbf
110100703 [0004b686] CudaPinnedPtr<T>::Realloc: cudaHostAlloc( ..., 28711564312 bytes, ... ) on thread 308870
110100707 [0004b686] ApplicationException ([0x00308870] AriocBase/../CudaCommon/CudaPinnedPtr.h 105): Unable to allocate page-locked system memory (CUDA "pinned" memory).  Please ensure that there is sufficient system memory to execute this program.

Is this information sufficient to develop an idea? I am not sure there is an additional log - I did not find any.

**Comment by RWilton** [comment]
The AriocP output log points to the problem.

As AriocP loads the reference-genome lookup tables, you can see the memory allocation for each table. All the tables are being placed in system RAM and mapped into the GPU address space.  (In CUDA terminology, they are "pinned".)

The genome base sequence (R) LUTs take only 2.2GB:

```
105923838 [0004b553] AriocBase::loadR: load R from disk...
105928190 [0004b553] AriocBase::loadR: loaded 25 R sequences: 2358955464 bytes (2.2GB) from 50 files in 4352ms (516.9MB/s)

```
But the H (hash table) and J (hash-table buckets) LUTs used for finding the seeds for read alignment consume much more memory:

```
105928190 [0004b553] AriocBase::loadHJ: load H and J LUTs from disk...
105940200 [0004b56f] tuLoadLUT::main: loaded 5368709120 bytes (5.0GB)
110047853 [0004b58f] tuLoadLUT::main: loaded 28623477755 bytes (26.7GB)
110100703 [0004b65d] tuLoadLUT::main: loaded 5368709120 bytes (5.0GB)

```
At this point, AriocP tries to load the next LUT, for which it needs another 26.7GB:

```
110100703 [0004b686] CudaPinnedPtr::Realloc: cudaHostAlloc( ..., 28711564312 bytes, ... ) on thread 308870
110100707 [0004b686] ApplicationException ([0x00308870] AriocBase/../CudaCommon/CudaPinnedPtr.h 105): Unable to allocate page-locked system memory (CUDA "pinned" memory). Please ensure that there is sufficient system memory to execute this program.

```
See the problem?  There's not enough free system RAM to load the final 26.7GB table.

The only solutions are to increase the amount of available system memory or to use smaller LUTs.

I would suggest that you monitor system memory utilization while AriocP is executing.  (A program like `top` or `htop` ought to suffice.)  If you're close to having enough memory, you might be able to unload some other concurrently-executing application and get AriocP to load successfully.

Alternatively, you can build smaller LUTs with AriocE.  You can limit the size of the LUTs by using AriocE to encode the LUTs with smaller `seed=` and/or `maxJ=` parameters.  There's a description of those parameters in the Arioc User Guide.

**Comment by claus-h-g** [comment]
Thank you very much for your prompt reply and detailed explanation.
I will continue on this test machine with smaller seed and maxJ parameters.
