### ISSUE TITLE
Consider putting source code under version control

### ISSUE THREAD

**Issue by standage** [RWilton/Arioc#5]
First I want to say thanks for publishing this project, for making the source code for stable releases available, and for your engagement on this issue tracker.

I'm curious if the decision to keep the source code out of version control is deliberate. I'm sure you're aware of the some of the convenient tools Github provides: browsing source code, viewing diffs between commits, commenting on source code or on commits/edits to the source code, supporting patch submissions, etc. If there were concerns about privacy or access control I would assume the source code for each release wouldn't be public. Are there other concerns about putting Arioc's source code under version control?

**Comment by RWilton** [comment]
The Arioc sources are public because we wrote journal articles about the software.

The source code is indeed under version control "internally" along with other related software projects.  We chose not to use github for versioning primarily because there has been very little public interest in modifying the code apart from getting it to build in various incarnations of Linux.

**Comment by standage** [comment]
Understood. It may be ambitious to expect that this would become a booming open source project, but on the other hand there’s probably nothing to lose by including the source code in the public-facing repo. #shrug

In any case, good work!

**Comment by antonkulaga** [comment]
@RWilton why cannot you just mirror it to github? Even for those people who do not have time to contribute there is sometimes a need to build from master as some nasty bugs can be fixed between releases

**Comment by standage** [comment]
Another benefit is that I would have been able to link directly to the lines in question in [this comment](https://github.com/RWilton/Arioc/issues/7#issuecomment-466525540).
